### ISSUE TITLE
Provide windows binaries

### ISSUE THREAD

**Issue by connected201** [jarmo/win32screenshot#35]
Hi, it's possible to provide windows binaries to download? (i don't know wow to compile ruby code). thanks.

**Comment by jarmo** [comment]
This gem does not have anything to compile since everything is pure Ruby code or precompiled binaries of ImageMagick.

Closing this. In case you have a specific problem then either write to StackOverflow or if you thinik that this is a problem/bug with this library, then create another issue.

**Comment by jarmo** [comment]
A little addendum - `win32screenshot` has a dependency [RAutomation](https://github.com/jarmo/RAutomation/) which has code, which will be compiled by Ruby during `gem install` or `bundle install` when using Bundler. Maybe you're having problem with compiling that library instead of `win32screenshot`? If that's the case then pay attention that `RAutiomation` supports only 32bit Ruby and 64bit version. This means that `win32screenshot` also works only on 32bit Ruby version unfortunately.

Download x86 (32bit) version of Ruby from here with Devkit (basically build toolchain) https://rubyinstaller.org/downloads/
